### PR TITLE
fix horizontal overflow

### PR DESCRIPTION
**Pull request by amanzrx4**

### CODE REVIEW

**Comment by steven-tey** [comment]
Hey, thanks for the PR! I'm a bit confused – what does this fix specifically? Can you send a screenshot of the before and after? 👀

**Comment by 2ne** [comment]
> Hey, thanks for the PR! I'm a bit confused – what does this fix specifically? Can you send a screenshot of the before and after? 👀

Using w-screen uses 100vw so if your page needs to scroll vertically then the width of the page becomes 100vw + scroll bar width. I'm guessing you use a mac so the horizontal scroll bars are not visible to you. On windows using chrome on your home page you can see vertical and horizontal scrolls bars.

**Comment by llegomark** [comment]
Great work on submitting this PR for horizontal overflow! I was actually in the process of working on a similar issue, but I see that you've already addressed it.

image

**Comment by amanzrx4** [comment]
Horizontal overflow looks annoying so you might want it fixed @steven-tey . Thanks for the clear explanation @2ne

**Comment by steven-tey** [comment]
Oh great point! I'm a dummy and forgot that Mac hides scrollbars by default 😅 

Thank you again for the PR – merging it now! :)

**Pull request merged**
